Forever-Pet/foreverpet-backend

src/main/java/com/hello/foreverpet/config/SwaggerConfig.java

SwaggerConfig
- Add Base Setting for use Swagger-Ui

feat(SwaggerConfig): Add SwaggerConfig

---

scripts/deploy.sh

CI Settings
- EC2 폴더에 직접 생성한 application.yml 등록

ci(CI Settings): CI Settings

---

src/main/java/com/hello/foreverpet/config/SwaggerConfig.java

Swagger Config add group , displayname

fix(Swagger Config): fix Swagger Config

---

src/main/resources/application-real.properties

Properties
- application-real-properties

feat(application-real-properties): application-real-properties

---

src/main/java/com/hello/foreverpet/Application.java
src/main/java/com/hello/foreverpet/auditing/BaseTimeEntity.java
src/main/java/com/hello/foreverpet/controller/ProductController.java
src/main/java/com/hello/foreverpet/domain/dto/Address.java
src/main/java/com/hello/foreverpet/domain/dto/Categories.java
src/main/java/com/hello/foreverpet/domain/dto/request/NewProductRequest.java
src/main/java/com/hello/foreverpet/domain/dto/request/UpdateProductRequest.java
src/main/java/com/hello/foreverpet/domain/dto/response/ProductResponse.java
src/main/java/com/hello/foreverpet/domain/entity/Product.java
src/main/java/com/hello/foreverpet/repository/ProductJpaRepository.java
src/main/java/com/hello/foreverpet/service/InitDataService.java
src/main/java/com/hello/foreverpet/service/ProductService.java

Product 관련 작업 프론트분들 요청으로 우선 먼저 진행한 몇가지 입니다.

Product CRU

---

src/main/java/com/hello/foreverpet/domain/entity/Product.java
src/main/java/com/hello/foreverpet/domain/entity/UserInfo.java

UserInfo Entity 설정 추가

---

scripts/deploy.sh
src/main/java/com/hello/foreverpet/controller/ProductController.java
src/main/java/com/hello/foreverpet/domain/dto/request/NewProductRequest.java
src/main/java/com/hello/foreverpet/domain/dto/response/ProductResponse.java
src/main/java/com/hello/foreverpet/domain/entity/Product.java
src/main/java/com/hello/foreverpet/domain/entity/UserInfo.java
src/main/java/com/hello/foreverpet/repository/CustomProductRepository.java
src/main/java/com/hello/foreverpet/repository/CustomProductRepositoryImpl.java
src/main/java/com/hello/foreverpet/service/InitDataService.java
src/main/java/com/hello/foreverpet/service/ProductService.java
src/test/java/com/hello/foreverpet/ProductControllerTest.java

ProductController
add orderBySold
add orderByNew

ProductController

---

src/main/java/com/hello/foreverpet/controller/ProductController.java
src/main/java/com/hello/foreverpet/domain/dto/request/NewProductRequest.java
src/main/java/com/hello/foreverpet/domain/dto/request/UpdateProductRequest.java
src/main/java/com/hello/foreverpet/domain/entity/Product.java
src/main/java/com/hello/foreverpet/domain/entity/UserInfo.java

Fix Product Categories
- fix Product Categories Request String to Enum

fix(Product): Product

---

.gitignore
build.gradle
src/main/java/com/hello/foreverpet/config/SwaggerConfig.java
src/main/java/com/hello/foreverpet/domain/dto/Categories.java
src/main/java/com/hello/foreverpet/domain/dto/request/NewProductRequest.java
src/main/java/com/hello/foreverpet/domain/entity/Product.java
src/main/java/com/hello/foreverpet/service/InitDataService.java
src/main/resources/application.yml
src/test/java/com/hello/foreverpet/ProductControllerTest.java

Add Data Init

---

src/main/java/com/hello/foreverpet/config/CorsConfig.java
src/main/java/com/hello/foreverpet/config/SpringSecurityConfig.java

fix(Cors Error): Cors Error

---

appspec.yml
scripts/deploy.sh
src/main/java/com/hello/foreverpet/domain/entity/Product.java
src/main/java/com/hello/foreverpet/repository/ProductJpaRepository.java
src/main/resources/application.yml
src/test/java/com/hello/foreverpet/ForeverpetApplicationTests.java

ci(CICD): CICD

---

src/main/java/com/hello/foreverpet/controller/AuthController.java
src/main/java/com/hello/foreverpet/controller/UserController.java
src/main/java/com/hello/foreverpet/domain/dto/request/UserSignupRequest.java
src/main/java/com/hello/foreverpet/domain/entity/UserInfo.java
src/main/java/com/hello/foreverpet/service/UserService.java
src/test/java/com/hello/foreverpet/UserControllerTest.java

fix(userLogin, socialLogin) : 소셜 로그인 및 유저 회원가입 관련 커밋

---

src/main/java/com/hello/foreverpet/config/CorsConfig.java

refactor(Fix CorsConfig): Fix CorsConfig

---

build.gradle

fix(gradle) : json gradle

---

build.gradle
src/main/java/com/hello/foreverpet/config/JwtSecurityConfig.java
src/main/java/com/hello/foreverpet/config/SecurityUtil.java
src/main/java/com/hello/foreverpet/config/SpringSecurityConfig.java
src/main/java/com/hello/foreverpet/controller/AuthController.java
src/main/java/com/hello/foreverpet/controller/UserController.java
src/main/java/com/hello/foreverpet/domain/dto/AuthorityList.java
src/main/java/com/hello/foreverpet/domain/dto/request/UserLoginRequest.java
src/main/java/com/hello/foreverpet/domain/dto/request/UserSignupRequest.java
src/main/java/com/hello/foreverpet/domain/dto/response/UserLoginResponse.java
src/main/java/com/hello/foreverpet/domain/entity/Authority.java
src/main/java/com/hello/foreverpet/domain/entity/UserInfo.java
src/main/java/com/hello/foreverpet/jwt/JwtAccessDeniedHandler.java
src/main/java/com/hello/foreverpet/jwt/JwtAuthenticationEntryPoint.java
src/main/java/com/hello/foreverpet/jwt/JwtCustomUser.java
src/main/java/com/hello/foreverpet/jwt/JwtFilter.java
src/main/java/com/hello/foreverpet/jwt/TokenProvider.java
src/main/java/com/hello/foreverpet/repository/UserInfoJpaRepository.java
src/main/java/com/hello/foreverpet/service/CustomUserDetailsService.java
src/main/java/com/hello/foreverpet/service/OAuthLoginService.java
src/main/java/com/hello/foreverpet/service/UserService.java

fix(gradle) : jwt token, login, signUp, emailCheck, login 테스트 api 추가 완료

---

src/main/java/com/hello/foreverpet/service/UserService.java

test(Merge): Merge

---

src/main/java/com/hello/foreverpet/controller/AuthController.java
src/main/java/com/hello/foreverpet/controller/UserController.java
src/main/java/com/hello/foreverpet/domain/dto/request/UserEmailCheckRequest.java
src/main/java/com/hello/foreverpet/domain/dto/request/UserUpdateRequest.java
src/main/java/com/hello/foreverpet/domain/entity/UserInfo.java
src/main/java/com/hello/foreverpet/service/UserService.java

fix(gradle) : usermodify 업데이트 문

---

src/main/java/com/hello/foreverpet/service/OAuthLoginService.java

fix(gradle) : 카카오 삭제여부 포인트 회원가입 기능 추가

---

src/main/java/com/hello/foreverpet/controller/UserController.java
src/main/java/com/hello/foreverpet/domain/dto/request/UserAddressRequest.java
src/main/java/com/hello/foreverpet/domain/dto/request/UserNewPasswordRequest.java
src/main/java/com/hello/foreverpet/domain/entity/UserInfo.java
src/main/java/com/hello/foreverpet/service/UserService.java

fix(gradle) : 주소 변경 및 비밀번호 변경 로직 변경

---

src/main/java/com/hello/foreverpet/controller/ProductController.java
src/main/java/com/hello/foreverpet/domain/dto/response/LoginUserProductResponse.java
src/main/java/com/hello/foreverpet/domain/entity/Cart.java
src/main/java/com/hello/foreverpet/domain/entity/Product.java
src/main/java/com/hello/foreverpet/domain/entity/UserInfo.java
src/main/java/com/hello/foreverpet/domain/entity/Wish.java
src/main/java/com/hello/foreverpet/service/ProductService.java
src/main/java/com/hello/foreverpet/service/UserService.java
src/test/java/com/hello/foreverpet/CartTest.java

User <-> Cart  OneToOne
Cart <-> Product OnetoMany

refactor(Cart, Wish): Cart, Wish

---

src/main/java/com/hello/foreverpet/controller/AuthController.java
src/main/java/com/hello/foreverpet/controller/UserController.java
src/main/java/com/hello/foreverpet/domain/dto/response/ErrorResponse.java
src/main/java/com/hello/foreverpet/domain/dto/response/UserModifyResponse.java
src/main/java/com/hello/foreverpet/handler/ControllerAdvice.java
src/main/java/com/hello/foreverpet/handler/ErrorCode.java
src/main/java/com/hello/foreverpet/handler/RuntimeExceptionHandler.java
src/main/java/com/hello/foreverpet/jwt/JwtAuthenticationEntryPoint.java
src/main/java/com/hello/foreverpet/repository/AuthorityJpaRepository.java
src/main/java/com/hello/foreverpet/service/InitDataService.java
src/main/java/com/hello/foreverpet/service/UserService.java
src/main/resources/application.yml

userService 및 Error핸들러 추가 했습니다
핸들러랑 ErrorCode Class 확인하시고 에러 소스 추가하시면됩니다

fix(gradle) : Error 핸들러 추가 및 user service 오류 response 추가

---

scripts/deploy.sh

fix(fix deploy.sh): fix deploy.sh

---

src/test/java/com/hello/foreverpet/AuthControllerTest.java
src/test/java/com/hello/foreverpet/ProductServiceTest.java

[fix : 빌드실패로 인한 Test 오류부분 주석처리]

fix : 빌드실패로 인한 Test 오류부분 주석처리

---

src/main/java/com/hello/foreverpet/domain/dto/response/UserPasswordResponse.java

fix(gradle) : password 결과값 name 수정
